pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:Luismika Lim/WEB2022Apr_P02_T3.git
          - cd RepoName.git
          - git push --mirror git@github.com:Luismika Lim/WEB2022Apr_P02_T3.git