pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:kamiislu/ZZFashion.git
          - cd RepoName.git
          - git push --mirror git@github.com:kamiislu/ZZFashion.git